title: LinkedIn Portfolio
description: My portfolio highlights integration of data structures and algorithms, demonstrating their application in LinkedIn. It covers market analysis, business use cases, potential challenges, suitable algorithms, and performance analysis.
# logo: /assets/logo.jpg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
