title: Algorithmic Problem Solving Portfolio
description: Networking platforms such as LinkedIn utilize Data Structures and Algorithms (DSA) to effectively manage and foster connections among a large number of users. DSA plays a crucial role in optimizing search, recommendations, and data management to improve user experience and platform performance on LinkedIn.
logo: /assets/img/logo.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
